### ISSUE TITLE
Add Open Font License

### ISSUE THREAD

**Issue by eliheuer** [huytd/haskplex-font#1]
Both [Source Code Pro](https://github.com/adobe-fonts/source-code-pro/blob/release/LICENSE.md) and [IBM Plex Mono](https://github.com/IBM/plex/blob/master/LICENSE.txt) use the Open Font License. 

This repo could include a license so others can fork it and make modifications. I suggest using the  [OFL](https://en.wikipedia.org/wiki/SIL_Open_Font_License).

**Comment by BoldMonday** [comment]
Correction: Haskplex **must** be released under the OFL.

Article 5 of the OFL supplied with IBM Plex states:
```
5) The Font Software, modified or unmodified, in part or in whole,
must be distributed entirely under this license, and must not be
distributed under any other license. The requirement for fonts to
remain under this license does not apply to any document created
using the Font Software.
```
Source: https://github.com/IBM/plex/blob/master/LICENSE.txt

**Comment by eliheuer** [comment]
@BoldMonday Thanks! I do know that, I just didn't want this issues to seem too demanding. :^)

**Comment by huytd** [comment]
Thanks guys! I did think about it but not sure which license to use at first.
I'll update the license.

**Comment by BoldMonday** [comment]
Perhaps it is a good idea to indulge yourself in these matters first before you start releasing work from others.

The [current license](https://github.com/huytd/haskplex-font/blob/master/LICENSE.txt) states:
`Copyright © 2017 Huy Tran. with Reserved Font Name "Haskplex"`

1. You are not allowed to remove the original copyright statements about IBM Plex.
2. You did not create Haskplex in 2017.

Please check the OFL FAQ on how to create a valid license:
https://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web#a8c83d32

**Comment by huytd** [comment]
My bad :( I'll make an update.

**Comment by huytd** [comment]
Alright, I put up another pull request for this, please help me review it https://github.com/huytd/haskplex-font/pull/4
Thanks all!
