### ISSUE TITLE
Create brew cask

### ISSUE THREAD

**Issue by davidosomething** [huytd/haskplex-font#3]
I've opened a PR to submit this to homebrew cask fonts so it can be installed as
```
brew cask install font-haskplex
```

https://github.com/Homebrew/homebrew-cask-fonts/pull/1885

**Comment by huytd** [comment]
Cool, thank you so much 🍻 :D

**Comment by huytd** [comment]
@davidosomething FYI, I just added a new Haskplex Nerd font, and change the folder structure a bit. You might want to update your brew cask PR to reflect this as well.

**Comment by davidosomething** [comment]
they rejected it for now -- needs more than 50 stars apparently! can re-open in the future

**Comment by huytd** [comment]
Oops, that's sad :(

**Comment by huytd** [comment]
OK, if anyone interested in a homebrew solution, please check my tap here: https://github.com/huytd/homebrew-cask-fonts/

```
$ brew tap huytd/cask-fonts

# Install Haskplex font
$ brew cask install font-haskplex

# Install Haskplex Nerd font
$ brew cask install font-haskplex-nerd
```
